- command_line_assistant/__main__.py
- command_line_assistant/config.py
- command_line_assistant/history.py
- command_line_assistant/utils.py
- config.toml
There were a couple of leftovers when we renamed the project from shellai to command-line-assistant, and also, we were handling how to create the folders and files in the wrong way.
> [RSPEED-240] Fix config and history wrong paths

- .packit.yaml
We are not supporting EPEL 8 for this project publication in the meantime. So there is no need to support it for now. Also, it will help us with using newer python versions.
> [RSPEED-241] Drop builds for EPEL 8

- command_line_assistant/config.py
We were passing a dict instead of a *Schema class for the config object
> Transform dict to schema config

- command_line_assistant/cli.py
- tests/test_cli.py
The stdin was not being appended to the query, which is a bug. This patch should fix it.
> Append stdin to the user query

- Makefile
- pdm.lock
- pyproject.toml
- tox.ini
This tox setup is mostly intended to execute python3.9 and python3.12 in our local setup without the need of waiting for CI to run the specific test.
> Add tox for local development testing

- command_line_assistant/config.py
The config class itself can also be a dataclass. We can convert it to make the code easier.
> Convert the config class to be a dataclass

- .packit.yaml
Introduce the tests jobs to the packit CI. 
Proposal: At the moment it is split between two jobs. One that will be used for simple sanity, functional tests that will run on container (which is much faster to provision). This is run automatically. The second run will be on the VM which sill be used for more complex e2e testing, this can be triggered by specifying the label. For example:
```
/packit test --labels e2e
```
> Initial tests CI PoC

- command_line_assistant/handlers.py
- pyproject.toml
The cost of computing these particular log messages is low, but it's a good idea to get in the habit of deferring the formatting.
> Enable flake8 log formatting rules

- CONTRIBUTING.md
Our new minimum Python version is 3.9.
> Update contributing doc for new Python min version (3.9)

- .github/workflows/unit-tests.yml
This avoids running the same job twice when pushing to PR branches.
> Only run tests on pushes to main not all branches

- .pre-commit-config.yaml
This is helpful when CI is failing to see what is causing the error.
[Example](https://results.pre-commit.ci/run/github/874195541/1732135149.aWpzfbCLS029zTLFkc9mrA)
> Add ruff-format-diff check to display what the formatter changed

- command_line_assistant/config.py
Support for slots in dataclasses was added in 3.10. The workaround we had was confusing the type checker (it's probably the type checker being dumb, but we can get by without using slots to simply things).
> Remove use of slots in dataclasses

- .github/workflows/sanity.yml
- .github/workflows/unit-tests.yml
- .pre-commit-config.yaml
- command_line_assistant/__main__.py
- command_line_assistant/config.py
- command_line_assistant/history.py
Fix a few bugs/errors discovered by the type checker.
Add type narrowing hints in the config classes to get accurate attribute checking.
Change default values that can be a `str` or `Path` object to `Path` objects.
Add a pre-commit check for easy local testing but use a GitHub action to run type checking in CI. Pre-commit CI doses not allow network access, which prevents installation of `pyright`.
Depends on #44.
> Add pyright sanity check

- .packit.yaml
Reason: the TF is not able to install artifact on the container. So we disable it for now, until we figure out how to install it (without copr installation in the test suite).
> Remove container testing from pipeline

- .pre-commit-config.yaml
- command_line_assistant/rendering/decorators/base.py
- command_line_assistant/rendering/decorators/colors.py
- command_line_assistant/rendering/decorators/style.py
- command_line_assistant/rendering/decorators/text.py
- command_line_assistant/rendering/render.py
- command_line_assistant/rendering/spinner.py
- pdm.lock
- tests/commands/test_query.py
- tests/rendering/decorators/test_colors.py
- tests/rendering/decorators/test_style.py
- tests/rendering/decorators/test_text.py
- tests/rendering/test_render.py
- tests/rendering/test_spinner.py
- tests/utils/test_cli.py
This rendering module aim to make the output of information easy and less complicated by enforcing a single class that we can plug new "decorators" to be used.
Currently, this rendering class has support for: colors, emoji, text wrap, font styles and a basic spinner to wait for responses.
Jira Issues:
-
Checklist
> Add an experimental rendering module for client

- command_line_assistant/dbus/constants.py
- data/release/clad.service
- data/release/com.redhat.lightspeed.conf
- data/release/config.toml
- packaging/command-line-assistant.spec
> Update specfile to include config from release dir

- command_line_assistant/dbus/interfaces.py
- tests/dbus/test_interfaces.py
The connect_signals method in our QueryContext was triggering the API requests twice (as expected), but this is not the behavior we want. This patch removes this functionality.
Jira Issues:
-
Checklist
> The connect_signals was triggered the API request twice

- .pre-commit-config.yaml
- command_line_assistant/rendering/decorators/colors.py
- command_line_assistant/rendering/decorators/style.py
- docs/source/conf.py
- packaging/command-line-assistant.spec
- pdm.lock
- pyproject.toml
> Remove colorama dep

- command_line_assistant/commands/query.py
- command_line_assistant/config/schemas.py
- command_line_assistant/dbus/interfaces.py
- command_line_assistant/dbus/structures.py
- command_line_assistant/logger.py
- data/development/config/command_line_assistant/config.toml
- tests/commands/test_query.py
- tests/conftest.py
- tests/test_logger.py
Now sysadmins can configure the audit logging capabilities for CLAD. The configuration is all set and configurable via the config.toml settings.
By default, all query and responses will be logged to the audit file.
The new settings for the logging configuration contains the following:
- Enable/disable query audit logging
- Enable/disable response audit logging
- The user who made the request
- A timestamp indicating when the request happened
- Ability for the sysadmin to enable/disable query/response for a certian user
Jira Issues:
- [RSPEED-129](https://issues.redhat.com/browse/RSPEED-129)
Checklist
> [RSPEED-129] Add audit logging capability to CLAD

- command_line_assistant/daemon/http/session.py
- tests/daemon/http/test_session.py
Adding two exception handling for the SSLAdapter class. One for the certificate not being valid, and the second one for the certificate missing on the system.
Without that, the user would receive a nasty error in the client and a not that helpful error in the journald logs.
Jira Issues:
- [RSPEED-388](https://issues.redhat.com/browse/RSPEED-388)
Checklist
> [RSPEED-388] Add exception handling for SSL certificates

- command_line_assistant/commands/history.py
- command_line_assistant/commands/query.py
- command_line_assistant/initialize.py
- command_line_assistant/rendering/base.py
- command_line_assistant/utils/renderers.py
- docs/source/utils/index.rst
- docs/source/utils/renderers.rst
- tests/commands/test_history.py
- tests/conftest.py
- tests/helpers.py
- tests/rendering/renders/test_spinner.py
- tests/rendering/renders/test_text.py
- tests/test_initialize.py
- tests/utils/test_renderers.py
> Small code refactor for outputting text

- command_line_assistant/commands/history.py
- command_line_assistant/dbus/interfaces.py
- command_line_assistant/history/plugins/local.py
- command_line_assistant/history/schemas.py
- command_line_assistant/logger.py
- tests/commands/test_history.py
- tests/conftest.py
- tests/dbus/test_interfaces.py
- tests/history/plugins/test_local.py
- tests/history/test_schemas.py
Jira Issues:
- [RSPEED-412](https://issues.redhat.com/browse/RSPEED-412)
Checklist
> [RSPEED-412] Add filter history option

- command_line_assistant/daemon/session.py
- docs/source/daemon/clad.rst
- docs/source/daemon/session.rst
- tests/daemon/test_session.py
This patch introduces a basic user session management that relies on the /etc/machine-id and the effective user id
Jira Issues:
- [RSPEED-136](https://issues.redhat.com/browse/RSPEED-136)
Checklist
> [RSPEED-136] Implement a basic user session management

- command_line_assistant/commands/query.py
- command_line_assistant/config/__init__.py
- command_line_assistant/constants.py
- command_line_assistant/daemon/http/session.py
- command_line_assistant/dbus/constants.py
- command_line_assistant/dbus/exceptions.py
- command_line_assistant/logger.py
- command_line_assistant/utils/files.py
- command_line_assistant/utils/renderers.py
- data/release/man/c.1
- data/release/man/clad.8
- docs/source/commands/index.rst
- docs/source/commands/record.rst
- docs/source/daemon/clad.rst
- docs/source/daemon/index.rst
- docs/source/daemon/session.rst
- docs/source/man/command-line-assistant.1.rst
- docs/source/utils/environment.rst
- docs/source/utils/files.rst
- docs/source/utils/index.rst
- tests/commands/test_query.py
- tests/utils/test_files.py
Jira Issues:
- [RSPEED-384](https://issues.redhat.com/browse/RSPEED-384)
Checklist
> [RSPEED-384] Add input field for query

- command_line_assistant/history/plugins/local.py
- tests/dbus/test_interfaces.py
Jira Issues:
- [RSPEED-446](https://issues.redhat.com/browse/RSPEED-446)
Checklist
> [RSPEED-446] Fix ordering from history results

- command_line_assistant/commands/history.py
- command_line_assistant/commands/query.py
- command_line_assistant/config/schemas.py
- command_line_assistant/daemon/database/models/history.py
- command_line_assistant/daemon/session.py
- command_line_assistant/dbus/context.py
- command_line_assistant/dbus/interfaces.py
- command_line_assistant/dbus/server.py
- command_line_assistant/history/base.py
- command_line_assistant/history/manager.py
- command_line_assistant/history/plugins/local.py
- command_line_assistant/logger.py
- command_line_assistant/utils/cli.py
- data/development/config/command-line-assistant/config.toml
- tests/commands/test_query.py
- tests/conftest.py
- tests/daemon/database/test_manager.py
- tests/daemon/test_session.py
- tests/dbus/test_context.py
- tests/dbus/test_interfaces.py
- tests/dbus/test_server.py
- tests/history/plugins/test_local.py
- tests/history/test_manager.py
- tests/test_logger.py
The user_id is a special way for us to control which record is tied to which user. This will allow us to be prepared for a multi-user environment.
Jira Issues:
- [RSPEED-433](https://issues.redhat.com/browse/RSPEED-433)
Checklist
> [RSPEED-433] Add user_id to history tables.

- command_line_assistant/utils/renderers.py
- tests/commands/test_query.py
- tests/test_initialize.py
- tests/utils/test_renderers.py
Error messages were going to stdout instead of stderr. This patch fixes this and redirect them to the correct stream.
Jira Issues:
- [RSPEED-465](https://issues.redhat.com/browse/RSPEED-465)
Checklist
> [RSPEED-465] Redirect to stderr instead of stdout for error msgs

- command_line_assistant/config/schemas/backend.py
- command_line_assistant/daemon/http/session.py
- data/development/config/command-line-assistant/config.toml
- data/release/xdg/config.toml
- tests/conftest.py
- tests/daemon/http/test_query.py
- tests/daemon/http/test_session.py
Now we can specify a proxy to route the request.
Jira Issues:
- [RSPEED-23](https://issues.redhat.com/browse/RSPEED-23)
Checklist
> [RSPEED-23] Add proxy setting for config.toml

- command_line_assistant/commands/chat.py
- command_line_assistant/daemon/database/models/chat.py
- command_line_assistant/exceptions.py
- command_line_assistant/rendering/renders/interactive.py
- command_line_assistant/utils/renderers.py
- data/development/config/command-line-assistant/config.toml
- docs/source/exceptions.rst
- docs/source/index.rst
- docs/source/rendering/renders/interactive.rst
- tests/commands/test_chat.py
- tests/rendering/renders/test_interactive.py
Now users can keep chatting in the same REPL sending and receiving messages.
Jira Issues:
- [RSPEED-585](https://issues.redhat.com/browse/RSPEED-585)
Checklist
> [RSPEED-585] Add simple and interactive chat session

- command_line_assistant/config/schemas/logging.py
- command_line_assistant/daemon/http/query.py
- command_line_assistant/dbus/interfaces/chat.py
- command_line_assistant/dbus/interfaces/history.py
- command_line_assistant/dbus/server.py
- command_line_assistant/initialize.py
- command_line_assistant/logger.py
- command_line_assistant/utils/cli.py
- data/development/config/command-line-assistant/config.toml
- data/release/selinux/clad.fc
- data/release/xdg/config.toml
- packaging/command-line-assistant.spec
- tests/config/schemas/test_logging.py
- tests/conftest.py
- tests/daemon/http/test_query.py
- tests/dbus/interfaces/test_chat.py
- tests/dbus/interfaces/test_history.py
- tests/test_initialize.py
- tests/test_logger.py
- tests/utils/test_cli.py
Rework the audit logging system to be less complex and accept dynamic attributes to be recorded.
Not all the database is set to use it, but the parts that are (chat and some history) are already working with it.
Jira Issues:
- [RSPEED-573](https://issues.redhat.com/browse/RSPEED-573)
- [RSPEED-577](https://issues.redhat.com/browse/RSPEED-577)
Checklist
> [RSPEED-573, RSPEED-577] Rework audit logging system

- command_line_assistant/commands/shell.py
- command_line_assistant/initialize.py
- command_line_assistant/integrations.py
- command_line_assistant/utils/cli.py
- command_line_assistant/utils/environment.py
- data/release/man/c.1
- data/release/man/clad.8
- docs/source/commands/index.rst
- docs/source/commands/shell.rst
- docs/source/index.rst
- docs/source/integrations.rst
- docs/source/man/command-line-assistant.1.rst
- poetry.lock
- pyproject.toml
- tests/commands/test_shell.py
- tests/test_initialize.py
- tests/utils/test_cli.py
- tests/utils/test_environment.py
Added a new shell command option to enable and disable shell
integrations. This command will hold, for now, the modifications that we
need to do in the user shell/terminal.
Currently, we only have one integration to control, which is the key
binding for the interactive mode.
Jira Issues:
- [RSPEED-586](https://issues.redhat.com/browse/RSPEED-586)
Checklist
> [RSPEED-586] Add a new shell command to handle integrations

- .github/workflows/build-manpages.yaml
This patch changes to a push event in order to build the manpages only when we push to the release branch. By default, we want to tag everytime from that branch, and not from main anymore.
Jira Issues:
-
Checklist
> Update to push event for building manpages

- command_line_assistant/commands/chat.py
- command_line_assistant/initialize.py
- command_line_assistant/terminal/parser.py
- command_line_assistant/utils/benchmark.py
- data/development/config/command-line-assistant/config.toml
- docs/source/utils/benchmark.rst
- docs/source/utils/index.rst
- tests/utils/test_benchmark.py
This is an optional decorator that will log debug messages with timing information about the functions. It will be used only when the log level is set to debug.
Jira Issues:
-
Checklist
> Add a timing decorator to help understand slowness

- command_line_assistant/commands/chat.py
- command_line_assistant/rendering/decorators/text.py
- tests/rendering/decorators/test_text.py
In this patch, the WriteOnceDecorator got renamed to
WriteOncePerSessionDecorator, to indicate that it will be written once
per session, not only once.
We also introduced the parent pid as a content of the file that get
written. This will help to identify that we are part of a session.
Jira Issues:
- [RSPEED-704](https://issues.redhat.com/browse/RSPEED-704)
Checklist
> [RSPEED-704] Show legal message on every shell session

- command_line_assistant/commands/history.py
- command_line_assistant/config/schemas/database.py
- command_line_assistant/daemon/database/manager.py
- data/development/config/command-line-assistant/config.toml
- docs/source/man/clad.8.rst
- packaging/command-line-assistant.spec
- tests/config/schemas/test_database.py
This patch introduces a mechanism for loading the database credentials
from systemd credentials. This allow the user to specify their
database username/password via systemd-creds, and the daemon will load
and use it.
It will only work if the username/password is empty in the config file.
If it is detected, we will use what is in the config.
Jira Issues:
- [RSPEED-657](https://issues.redhat.ocm/browse/RSPEED-657)
Checklist
> [RSPEED-657] Add ability to load credentials from systemd

- command_line_assistant/commands/base.py
- command_line_assistant/commands/chat.py
Jira Issues:
- [RSPEED-656](https://issues.redhat.com/browse/RSPEED-656)
Checklist
> [RSPEED-656] Non default value for with output

- command_line_assistant/commands/chat.py
- command_line_assistant/rendering/decorators/text.py
- command_line_assistant/terminal/parser.py
- command_line_assistant/terminal/reader.py
- command_line_assistant/utils/files.py
- tests/terminal/test_parser.py
- tests/utils/test_files.py
Before, we were reverting the list and that was causing trouble while trying to read the last terminal output. Now, we are trying to convert the index to a negative number.
Jira Issues:
-
Checklist
> Fix search ordering in last output function

- command_line_assistant/initialize.py
- tests/test_initialize.py
Try to handle keyboardinterrupt in the top-level call (initialize) to prevent a traceback being shown to the user.
Jira Issues:
-
Checklist
> Add KeyboardInterrupt exception catch to top-level call

- command_line_assistant/commands/chat.py
- command_line_assistant/commands/history.py
- command_line_assistant/dbus/exceptions.py
- command_line_assistant/history/base.py
- command_line_assistant/history/manager.py
- command_line_assistant/history/plugins/local.py
- command_line_assistant/initialize.py
- tests/commands/test_chat.py
- tests/commands/test_history.py
- tests/history/plugins/test_local.py
- tests/history/test_manager.py
- tests/test_initialize.py
This patch introduces a small handler to show a message to the user in
case the history is not enabled during the history calls.
Before this patch, a badly formatted error message would be used
instead, which is not helpful.
Jira Issues:
- [RSPEED-632](https://issues.redhat.com/browse/RSPEED-632)
Checklist
> [RSPEED-632] Add message when history is not enabled

- command_line_assistant/commands/shell.py
- command_line_assistant/integrations.py
- tests/commands/test_shell.py
It will be more tricky to handle this mode. For now, let's just skip it and avoid bugs.
Jira Issues:
-
Checklist
> Remove persistent capture mode (for now)

- .packit.yaml
Switch testing to 'main' cla-tests branch and use level1 test suite
Ref: https://issues.redhat.com/browse/RSPEED-725
-
Checklist
> [Packit] Switch testing to 'main' cla-tests branch and use level1 test suite

- command_line_assistant/commands/shell.py
- command_line_assistant/integrations.py
- command_line_assistant/terminal/reader.py
- tests/commands/test_shell.py
- tests/terminal/test_reader.py
> Fix incorrect use of marker in terminal reader

- packaging/command-line-assistant.spec
To give users another option to use our tooling, we are renaming the main binary to `cla` and giving a symlink to `c` to keep the usage the same.
Jira Issues:
-
Checklist
> Add cla binary and a symlink for c

- data/release/xdg/config.toml
The database schema was referencing the `user` key instead of `username`
Jira Issues:
- [RSPEED-773](https://issues.redhat.com/browse/RSPEED-773)
- [RSPEED-774](https://issues.redhat.com/browse/RSPEED-774)
Checklist
> [RSPEED-773, RSPEED-774] Fix incorrect key on database schema

- command_line_assistant/daemon/database/repository/base.py
- command_line_assistant/dbus/interfaces/chat.py
We had a bug where the condition was always returning True and causing users to share history
Jira Issues:
-
Checklist
> Fix 'where' conditions for sqlalchemy

- command_line_assistant/commands/history.py
- command_line_assistant/daemon/database/models/history.py
- command_line_assistant/daemon/database/repository/base.py
- command_line_assistant/dbus/interfaces/history.py
- command_line_assistant/dbus/structures/history.py
- command_line_assistant/history/base.py
- command_line_assistant/history/manager.py
- command_line_assistant/history/plugins/local.py
- tests/commands/test_history.py
- tests/conftest.py
- tests/dbus/interfaces/test_history.py
- tests/dbus/structures/test_history.py
- tests/history/test_manager.py
We were missing a filter option to let users filter out by specific chats. This patch introduces the --from-chat cli switch to add that.
Jira Issues:
- [RSPEED-780](https://issues.redhat.com/browse/RSPEED-780)
- [RSPEED-782](https://issues.redhat.com/browse/RSPEED-782)
Checklist
> [RSPEED-780, RSPEED-782] Add a --from-chat switch to history to filter out conversation

- command_line_assistant/commands/chat.py
- tests/commands/test_chat.py
If we only have one character as input from either the query_string or stdin, let's preven't it from happening as it won't provide much value.
Jira Issues:
- [RSPEED-654](https://issues.redhat.com/browse/RSPEED-654)
Checklist
> [RSPEED-654] Prevent one character input from query_string and stdin

- data/release/dbus/com.redhat.lightspeed.conf
Currently, the dbus policies were too open. We let all users acquire the bus name, which can be problematic.
Jira Issues:
- [RSPEED-799](https://issues.redhat.com/browse/RSPEED-799)
Checklist
> [RSPEED-799] Fix dbus permissions for clad

- command_line_assistant/commands/chat.py
- tests/commands/test_chat.py
Jira Issues:
- [RSPEED-796](https://issues.redhat.com/browse/RSPEED-796)
Checklist
> [RSPEED-796] Disallow empty query arguments for query_string and stdin

- data/release/dbus/com.redhat.lightspeed.conf
This field is not present in RHEL 9.6, so we are removing it from here.
Jira Issues:
-
Checklist
> Remove selinux context from dbus policy

- command_line_assistant/daemon/http/query.py
- tests/daemon/http/test_query.py
The HTTP responses containing errors are formatted in a list instead of
a single top-level dictionary.
This fixes the `🙁 'detail'` error when connecting to stage.
> Extract error messages from HTTP responses

- command_line_assistant/initialize.py
- tests/test_initialize.py
Jira Issues:
- [RSPEED-812](https://issues.redhat.com/browse/RSPEED-812)
Checklist
> [RSPEED-812] Add exception handling for RuntimeError

- Makefile
- command_line_assistant/constants.py
- data/release/man/c.1
- data/release/man/clad.8
- data/release/selinux/clad.te
- docs/source/conf.py
- packaging/command-line-assistant.spec
- pyproject.toml
> Prepare for release v0.3.1

- .gitignore
pyenv uses a ".python-version" file to track the version of python to use when in the current directory.
> Ignore .python-version file

- command_line_assistant/commands/chat.py
- command_line_assistant/rendering/renders/interactive.py
- tests/commands/test_chat.py
- tests/rendering/renders/test_interactive.py
The '.exit' operation was killing the process with exit code as 1, which is not ideal and correct. This patch fix it to exit with 0 instead.
Jira Issues:
- [RSPEED-768](https://issues.redhat.com/browse/RSPEED-768)
Checklist
> [RSPEED-768] Fix '.exit' from interactive mode

- command_line_assistant/utils/cli.py
Jira Issues:
- [RSPEED-859](https://issues.redhat.com/browse/RSPEED-859)
Checklist
> [RSPEED-859] Prevent abbrev in argparse

- .github/release.yml
- .github/workflows/enforce_labels.yml
- .github/workflows/jira-links.yml
This patch introduces some workflows to help us identify which PRs are necessary to push in a changelog or not. With the labels tagging, we can filter out PRs that does not need to be included in the changelog.
Jira Issues:
- [RSPEED-817](https://issues.redhat.com/browse/RSPEED-817)
Checklist
> [RSPEED-817] Add label automation to help in release changelog

- data/release/selinux/clad.te
This allows clad to create tempfs files (such as mmap files).
Fixes: [RSPEED-568](https://issues.redhat.com/browse/RSPEED-568)
> [RSPEED-568] Add tmpfs SELinux domain

- command_line_assistant/commands/history.py
- command_line_assistant/dbus/interfaces/chat.py
- tests/commands/test_history.py
- tests/dbus/interfaces/test_chat.py
In this patch, we are adding a call to the chat bus to figure out if there is any chat available with a given name for a user.
Jira Issues:
- [RSPEED-829](https://issues.redhat.com/browse/RSPEED-829)
Checklist
> [RSPEED-829] Add check in clear(-all) to check if there is any chat to clean

- command_line_assistant/rendering/renders/interactive.py
- tests/rendering/renders/test_interactive.py
* With #301 patch the StopInteractiveMode exception gets handled explicitly with an intention to not do anything else with it
* The exception message is now redundant due to that and might cause unnecessary confusion
Jira Issues:
-
Checklist
> Remove redundant exception message

- CONTRIBUTING.md
Our contributing guide had old and outdated sections and information. This patch clean up the guide.
Jira Issues:
-
Checklist
> Remove outdated sections from CONTRIBUTING.md

- command_line_assistant/rendering/renders/markdown.py
- tests/rendering/renders/test_markdown.py
This updates the coloring in MarkdownRenderer class to make the text more likely to be seen by the user and not cause any harm in the eyes.
Jira Issues:
- [RSPEED-925](https://issues.redhat.com/browse/RSPEED-925)
Checklist
> [RSPEED-925] Update colors in MarkdownRenderer to make the text more visible

- command_line_assistant/utils/files.py
The legal message was not being displayed on every session as we were not updating the file consistently.
This patch fixes it.
Jira Issues:
- [RSPEED-823](https://issues.redhat.com/browse/RSPEED-823)
Checklist
> [RSPEED-823] Fix legal message not showing up on each session

- .vscode/launch.json
We were missing a property in our launch.json, and due to that, we couldn't execute tests in debug mode.
Jira Issues:
-
Checklist
> Add missing property and config to launch.json

- command_line_assistant/daemon/database/manager.py
If the history database is SQLite, ensure the parent directory is
created before creating the database. This should be a noop if the
directory already exists, but enables the history to exist in alternate
directories (like ~/.local/state/command-line-assistant).
> Create the history.db parent directory

- .github/workflows/release.yml
- Makefile
- packaging/command-line-assistant.spec
This will create a custom tarball with only the necessary items for our release. No more development/project specific will be included in the tarball.
The github ones will still be there, but ours will be refined.
Jira Issues:
- [RSPEED-898](https://issues.redhat.com/browse/RSPEED-898)
Checklist
> [RSPEED-898] Generate tarball on every tag release

- .vscode/launch.json
- command_line_assistant/utils/environment.py
Change the get_xdg_config_path function to detect and return the first directory listed in the variable that exists.
> Include both ~/.config and data/development config

- command_line_assistant/daemon/database/models/base.py
- command_line_assistant/daemon/database/models/chat.py
- command_line_assistant/daemon/database/models/history.py
SQLAlchemy 2.x has better support for it, but since we also support version 1.4.x, there is not much support for type annotations there.
Jira Issues:
-
Checklist
> Revert type annotations for SQLAlchemy

- .packit.yaml
* We have decided to branch our test suite to have more flexibility when reacting to the upstream changes
* main branch hosts tests for downstream/compose builds
* develop branch is shifted left to address potential changes to the upstream codebase, aiming to always green suite for both upstream and downstream
Jira Issues:
-
Checklist
> Point the test job to the `develop` branch

- command_line_assistant/commands/chat.py
- command_line_assistant/commands/shell.py
- command_line_assistant/utils/files.py
- tests/commands/test_chat.py
- tests/commands/test_shell.py
- tests/conftest.py
- tests/utils/test_files.py
This locking mechanism is intended to be used alongside the terminal capture feature from `shell --enable-capture`.
This generic file locking mechanism aims to do the following:
- Create a lock file with a given name
- Lock the file so no users can edit
- Allow only the $USER to read/write to it
The class can also be used as a contextmanager or regulary accessing its methods `acquire` and `release`.
Jira Issues:
- [RSPEED-770](https://issues.redhat.com/browse/RSPEED-770)
Checklist
> [RSPEED-770] Add general file locking mechanism

- command_line_assistant/commands/history.py
- tests/commands/test_history.py
In case nothing is supplied when the user type `c history`, we will be defaulting it to trigger the `--all` flag.
Jira Issues: [RSPEED-1118](https://issues.redhat.com/browse/RSPEED-1118)
-
Checklist
> [RSPEED-1118] Default to --all in history command

- command_line_assistant/commands/chat.py
- command_line_assistant/dbus/interfaces/chat.py
- command_line_assistant/dbus/structures/chat.py
- tests/dbus/interfaces/test_chat.py
This patch introduces a couple new models to submit them to the backend to provide more refined context about the user system.
Jira Issues:
- [RSPEED-991](https://issues.redhat.com/browse/RSPEED-991)
Checklist
> [RSPEED-991] Submit systeminfo to backend as part of context

- command_line_assistant/dbus/interfaces/chat.py
- tests/dbus/interfaces/test_chat.py
We were passing the wrong format to the backend with the terminal context. That was causing the API to reject our request with a 403.
Jira Issues:
- [RSPEED-1150](https://issues.redhat.com/browse/RSPEED-1150)
Checklist
> [RSPEED-1150] Fix unprocessable entity request for inference

- command_line_assistant/commands/shell.py
- tests/commands/test_shell.py
When installing the bash snippet that enables the interactive keybinding, check for the presence of ".bashrc.d" in the user's bash rc files. If no mention of the directory is found, a warning is printed, informing the user that shell integration requires the use of a snippet that loads files from ~/.bashrc.d.
Jira Issues:
- [RSPEED-952](https://issues.redhat.com/browse/RSPEED-952)
> [RSPEED-952] Warn if .bashrc.d missing

- command_line_assistant/client.py
- command_line_assistant/commands/base.py
- command_line_assistant/commands/chat.py
- command_line_assistant/commands/feedback.py
- command_line_assistant/commands/history.py
- command_line_assistant/rendering/renders/markdown.py
- command_line_assistant/rendering/renders/spinner.py
- command_line_assistant/rendering/renders/text.py
- command_line_assistant/utils/cli.py
- command_line_assistant/utils/renderers.py
- data/release/man/c.1
- pyproject.toml
- tests/commands/test_chat.py
- tests/rendering/renders/test_markdown.py
- tests/rendering/renders/test_text.py
PlainTextRenderer and PlainMarkdownRenderer subclass TextRenderer and MarkdownRenderer respectively. They disregard any decorators that might be added to them by other code and print plain text or raw, unformatted markdown as the case may be.
The various renderer factory functions (create_text_renderer and create_markdown_renderer) have been updated with a keyword argument of 'plain' with a default value of false (preserving existing behavior). If plain is true, the factory function returns a Plain subclass instead of the rich-formatted class. The rest of the render flow remains unmodified. The various calls to create_text_renderer and create_markdown_renderer function have been updated to pass in the value of 'args.plain' wherever possible. This will enable plain rendering when the …
> [RSPEED-816] Add support for plain, simple output

- command_line_assistant/daemon/database/manager.py
- tests/config/schemas/test_database.py
This patch is intended to fix the permission inheritance of the sqlite
database when it is being created for the first time.
Jira Issues:
- [RSPEED-1073](https://issues.redhat.com/browse/RSPEED-1073)
Checklist
> [RSPEED-1073] Limit permission for history database to own user

- data/release/systemd/clad.tmpfiles.conf
- packaging/command-line-assistant.spec
Fixes the following lint when installing on Bootable Containers:
```
Lint warning: var-tmpfiles: Found content in /var missing systemd tmpfiles.d entries:
d /var/lib/command-line-assistant 0700 root root - -
```
Jira Issues:
- [RSPEED-1626](https://issues.redhat.com/browse/RSPEED-1626) (does not fix this issues but should helps with it)
Checklist
> RSPEED-1626: packaging: Add tmpfiles.d config for /var folder

- packaging/command-line-assistant.spec
Since the introduction of the tmpfiles.d config to allow image mode testing, we missed to add this line to our %files section of the rpm.
Jira Issues:
- [RSPEED-1626](https://issues.redhat.com/browse/RSPEED-1626)
Checklist
> [RSPEED-1626] Add missing line for %files in rpmbuild

- Containerfile
- Makefile
- container-images/default.Containerfile
- scripts/prepare_release.py
This patch introduces a Containerfile that is specialized to build CLA through Konflux and other ways.
This will allow us to push CLA through official Red Hat registry.
Jira Issues:
- [RSPEED-1065](https://issues.redhat.com/browse/RSPEED-1065)
- [RSPEED-1626](https://issues.redhat.com/browse/RSPEED-1626)
Checklist
> [RSPEED-1065, RSPEED-1626] Add Containerfile for CLA

- command_line_assistant/commands/chat.py
Adding a new horizontal line after the spinner text to make it more readable
Jira Issues:
- [RSPEED-1564](https://issues.redhat.com/browse/RSPEED-1564)
Checklist
> [RSPEED-1564] Add horizontal line after spinner message

- command_line_assistant/client.py
- command_line_assistant/utils/cli.py
- tests/test_client.py
There was a regression between 0.3.x and 0.4.0 that the `c history` was not defaulting to `c history --all` when executed, but rather, showing the help message.
Jira Issues:
-
Checklist
> Fix regression for `c history`

- command_line_assistant/commands/chat.py
We had a typo in the total input size warning message we emit when the total attachment size is over 32k
Jira Issues:
- [RSPEED-1796](https://issues.redhat.com/browse/RSPEED-1796)
Checklist
> [RSPEED-1796] Fix typo in warning message for total input size

- .pre-commit-config.yaml
pre-commit is being too noise trying to update the modules every week. Sometimes it only updates 1 repository. To avoid having to merge every single week the updates, let's run this monthly instead
Jira Issues:
-
Checklist
> Change pre-commit autoupdate schedule to monthly

- command_line_assistant/daemon/http/query.py
- tests/daemon/http/test_query.py
When the submit method throws an error, catch OSErrors and inspect the message. If it contains "/etc/pki/consumer/cert.pem" (the default file path for the RHSM consumer certificate), assume the system is not registered with RHSM and raise a custom error string recommending the user connect the system using rhc.
```
[link@localhost ~]$ c "What is RHEL Lightspeed?"
⁺₊+ Asking RHEL Lightspeed
System is not registered with Red Hat. Run `subscription-manager register` or `rhc connect` and try again.
[link@localhost ~]$
```
Fixes: RSPEED-1762
Fixes: RHEL-102629
Fixes: #335
> [RSPEED-1762] Catch OSError being thrown by submit method

- pyproject.toml
- uv.lock
Pin dasbus and pygobject versions.
- pygobject 3.40.0 crashes with a FFI function call to glib.
- dasbus 1.4 is the oldest possible version of dasbus available, so it's our baseline dependency.
This PR is committing a patch I've been cherry-picking around to various other development branches in order for the FFI function calls to work into GIO, so I figured I should actually commit it!
> Pin dasbus to 1.4 and pygobject to 3.40.1

- container-images/default.Containerfile
- pyproject.toml
Moved the pygobject dependency back to the `dev` dependencies as it was causing problems with the konflux build.
Jira Issues:
-
Checklist
> Fix container builds in Konflux

- .tekton/pipeline-build.yaml
- .tekton/pull_request.yaml
- .tekton/push.yaml
- container-images/default.Containerfile
Adjusting the .tekton build pipeline to perform multi-arch builds for CLA in x86_64 and arm64.
Jira Issues:
-
Checklist
> Add multi-arch builds in Konflux
