rhel-lightspeed/command-line-assistant

.pre-commit-config.yaml
Weekly updates are a bit too frequent.
=> Change pre-commit config update frequency

.github/workflows/unit-tests.yml, CONTRIBUTING.md, command_line_assistant/daemon/clad.py, data/systemd/clad.service, data/systemd/clad@.socket, packaging/command-line-assistant.spec, pdm.lock, pyproject.toml
This patch introduces an initial setup for clad (Command Line Assistant Daemon).
=> [RSPEED-299] Initial setup for clad

Makefile, command_line_assistant/dbus/constants.py
=> Change DBUS service name

.packit.yaml
=> Enable copr builds in develop

Makefile, command_line_assistant/dbus/constants.py, command_line_assistant/dbus/server.py, data/development/systemd/clad-devel.service, data/release/com.redhat.lightspeed.conf, tests/dbus/test_server.py
=> Switch to system bus instead of session bus

schemas/command-line-assistant-v0.1.json
Jira Issues:
- [RSPEED-284](https://issues.redhat.com/browse/RSPEED-284)
- [RSPEED-285](https://issues.redhat.com/browse/RSPEED-285)
Checklist
=> [RSPEED-284, RSPEED-285] Add schema for input/output queries and history

command_line_assistant/daemon/http/query.py, tests/daemon/http/test_query.py
=> Query against rlsrag

.readthedocs.yaml, docs/requirements.txt
=> Add readthedocs build support

.readthedocs.yaml
=> Fix readthedocs yaml config

docs/source/conf.py
=> Fix conf path

CONTRIBUTING.md
=> Small modifications to CONTRIBUTING.md

command_line_assistant/commands/query.py
=> Update legal message

.readthedocs.yaml, docs/requirements.txt
=> Add new dependencies for readthedocs to build

docs/requirements.txt
=> Missing dep for readthedocs

command_line_assistant/commands/history.py, command_line_assistant/commands/query.py, command_line_assistant/utils/cli.py, data/release/man/c.1, data/release/man/clad.8, docs/source/conf.py, docs/source/man/clad.8.rst, docs/source/man/command-line-assistant.1.rst, tests/commands/test_query.py
The manpages are updated to ship updated version for RH1
Jira Issues:
- [RSPEED-437](https://issues.redhat.com/browse/RSPEED-437)
Checklist
=> [RSPEED-437] Update manpages for RH1

packaging/command-line-assistant.spec
Updated rpm changelog to reflect the additions from 0.1.0 and the upcoming 0.2.0 release
Jira Issues:
- [RSPEED-418](https://issues.redhat.com/browse/RSPEED-418)
Checklist
=> [RSPEED-418] Update rpm changelog

command_line_assistant/initialize.py, packaging/command-line-assistant.spec, tests/test_initialize.py
Jira Issues:
- [RSPEED-463](https://issues.redhat.com/browse/RSPEED-463)
Checklist
=> [RSPEED-463] Fix returncode when running commands

.gitignore, command_line_assistant/logger.py, data/release/selinux/Makefile, data/release/selinux/clad.fc, data/release/selinux/clad.if, data/release/selinux/clad.te, packaging/command-line-assistant.spec
Jira Issues:
- [RHEL-68636](https://issues.redhat.com/browse/RHEL-68636)
- [RHEL-68637](https://issues.redhat.com/browse/RHEL-68637)
Checklist
=> [RHEL-68636, RHEL-68637] Update packaging to include selinux custom policy

command_line_assistant/daemon/http/query.py
=> Remove caret handling from query submission

.packit.yaml, command_line_assistant/daemon/database/models/base.py, command_line_assistant/daemon/database/models/history.py, data/development/config/command-line-assistant/config.toml, packaging/command-line-assistant.spec, tests/daemon/database/models/test_base.py
=> Try fedora builds

data/release/xdg/config.toml
=> Uncomment output settings in release config

command_line_assistant/daemon/database/models/base.py, packaging/command-line-assistant.spec
Jira Issues:
- [RSPEED-491](https://issues.redhat.com/browse/RSPEED-491)
Checklist
=> [RSPEED-491] Change import location for SQLAlchemy

command_line_assistant/constants.py, data/release/selinux/clad.te, packaging/command-line-assistant.spec, pyproject.toml
=> Release v0.2.1

.gitlab-ci.yml
Jira Issues:
- RSPEED-495](https://issues.redhat.com/browse/RSPEED-495)
-
Checklist
=> [RSPEED-495] Specify tag for selecting runners

packaging/command-line-assistant.spec
Jira Issues:
- [RSPEED-522](https://issues.redhat.com/browse/RSPEED-522)
Checklist
=> [RSPEED-522] Add noreplace to config file in specfile

command_line_assistant/constants.py, data/release/selinux/clad.te, packaging/command-line-assistant.spec, pyproject.toml
=> Release v0.2.2

command_line_assistant/commands/query.py, command_line_assistant/daemon/http/query.py, command_line_assistant/dbus/interfaces.py, command_line_assistant/dbus/structures.py, command_line_assistant/initialize.py, command_line_assistant/utils/cli.py, command_line_assistant/utils/files.py, data/development/config/command-line-assistant/config.toml, tests/commands/test_query.py, tests/daemon/http/test_query.py, tests/dbus/test_interfaces.py, tests/test_initialize.py, tests/utils/test_cli.py, tests/utils/test_files.py
This will help us down the road when we start manipulating context for prompt engineering.
Jira Issues:
- [RSPEED-506](https://issues.redhat.com/browse/RSPEED-506)
Checklist
=> [RSPEED-506] Little rework to start sending context alongside question

data/release/man/c.1, data/release/man/clad.8, docs/source/man/clad.8.rst
=> Update manpages with new information

command_line_assistant/commands/chat.py, command_line_assistant/dbus/constants.py, command_line_assistant/dbus/exceptions.py, command_line_assistant/dbus/interfaces.py, command_line_assistant/dbus/server.py, command_line_assistant/initialize.py, command_line_assistant/utils/cli.py, data/release/dbus/com.redhat.lightspeed.chat.service, data/release/dbus/com.redhat.lightspeed.conf, data/release/man/c.1, docs/source/commands/chat.rst, docs/source/commands/index.rst, docs/source/commands/query.rst, docs/source/man/clad.8.rst, docs/source/man/command-line-assistant.1.rst, packaging/command-line-assistant.spec, tests/commands/test_chat.py, tests/dbus/test_interfaces.py, tests/dbus/test_server.py, tests/test_initialize.py, tests/utils/test_cli.py
Jira Issues:
- [RSPEED-551](https://issues.redhat.com/browse/RSPEED-551)
Checklist
=> [RSPEED-551] Rename all instances of public "query" to "chat"

command_line_assistant/rendering/renders/spinner.py, tests/rendering/renders/test_spinner.py
=> Minor improvements to spinner

data/release/xdg/config.toml
Jira Issues:
- [RSPEED-573](https://issues.redhat.com/browse/RSPEED-573)
Checklist
=> [RSPEED-573] Default audit to false

docs/source/man/clad.8.rst
=> Fix typoos for CLAD man page documentation

data/release/systemd/clad.service
Jira Issues:
- [RSPEED-489](https://issues.redhat.com/browse/RSPEED-489)
Checklist
=> [RSPEED-489] Increase timeout secs

command_line_assistant/config/schemas/logging.py, command_line_assistant/daemon/clad.py, command_line_assistant/dbus/server.py, command_line_assistant/initialize.py, command_line_assistant/logger.py, data/development/config/command-line-assistant/config.toml, tests/conftest.py, tests/daemon/test_clad.py, tests/test_logger.py
=> Fix logging and audit

.pre-commit-config.yaml, packaging/command-line-assistant.spec
Jira Issues:
- [RSPEED-499](https://issues.redhat.com/browse/RSPEED-499)
Checklist
=> [RSPEED-499] Fix rpmlint

.github/workflows/unit-tests.yml, .gitlab-ci.yml, Makefile, sonar-project.properties
=> Fix sonarqube - round 1

.packit.yaml
=> Track the develop branch for cla tests

Makefile
=> [RSPEED-579] Update makefile to install poetry

.gitlab-ci.yml, Makefile
=> [RSPEED-579] Add deps gitlab

.gitlab-ci.yml
=> [RSPEED-579] Fix gitlab-ci -- remove sudo

.gitlab-ci.yml, tests/utils/test_cli.py
=> [RSPEED-579] Fix test pipeline

command_line_assistant/config/schemas/backend.py, command_line_assistant/config/schemas/database.py, command_line_assistant/daemon/database/models/chat.py, command_line_assistant/daemon/database/repository/base.py, command_line_assistant/dbus/interfaces/chat.py, command_line_assistant/dbus/interfaces/history.py, command_line_assistant/history/manager.py, command_line_assistant/initialize.py
=> [RSPEED-579] Fix sonarqube issues

command_line_assistant/commands/chat.py, command_line_assistant/terminal/reader.py, tests/commands/test_chat.py
=> Fix typing_extension and name change for chat command

command_line_assistant/commands/chat.py, command_line_assistant/commands/history.py, data/release/man/c.1, data/release/man/clad.8, tests/commands/test_chat.py
Jira Issues:
- [RSPEED-409](https://issues.redhat.com/browse/RSPEED-409)
Checklist
=> [RSPEED-409] Add raw mode

scripts/prepare_release.py
=> Add simple prepare release script

command_line_assistant/commands/history.py, command_line_assistant/dbus/exceptions.py, command_line_assistant/dbus/interfaces/history.py, tests/commands/test_history.py, tests/dbus/interfaces/test_history.py
=> Add error handling for history command

data/release/selinux/clad.fc, data/release/selinux/clad.if, data/release/selinux/clad.te, packaging/command-line-assistant.spec
Jira Issues:
- [RSPEED-485](https://issues.redhat.com/browse/RSPEED-485)
Checklist
=> [RSPEED-485] Fix selinux policy configs

packaging/command-line-assistant.spec
Jira Issues:
- [RSPEED-592](https://issues.redhat.com/browse/RSPEED-592)
Checklist
=> [RSPEED-592] Fix file permissions

command_line_assistant/commands/history.py, tests/commands/test_history.py
=> Improve error message for missing history

command_line_assistant/commands/chat.py
=> Fix none values in stdin and query_string

command_line_assistant/rendering/renders/interactive.py
There was a typo in the interactive session message
Jira Issues:
-
Checklist
=> Fix typo in interactive session message

command_line_assistant/commands/chat.py, command_line_assistant/commands/history.py, command_line_assistant/rendering/renders/markdown.py, command_line_assistant/rendering/renders/text.py, command_line_assistant/utils/renderers.py, docs/source/rendering/renders/index.rst, docs/source/rendering/renders/markdown.rst, tests/commands/test_chat.py, tests/commands/test_history.py, tests/rendering/renders/test_markdown.py
=> Markdown renderer

data/release/man/c.1, data/release/man/clad.8, docs/source/man/clad.8.rst, docs/source/man/command-line-assistant.1.rst
Jira Issues:
- [RSPEED-648](https://issues.redhat.com/browse/RSPEED-648)
Checklist
=> [RSPEED-648] Update bug page report

command_line_assistant/commands/shell.py, command_line_assistant/integrations.py
=> Fix contents of persistent-capture

poetry.lock
=> Poetry lock maintenance

command_line_assistant/terminal/reader.py, tests/terminal/test_reader.py
Before we were not setting the terminal size when we spawned a new tty for capturing the output, that caused the lines to wrap and not being processed properly.
This patch fixes it by reading the terminal size before we enter the new tty.
Jira Issues:
- [RSPEED-728](https://issues.redhat.com/browse/RSPEED-728)
Checklist
=> [RSPEED-728] Fix terminal line wrapping when in terminal capture mode

command_line_assistant/logger.py
As requested by QE, we are including a null-character prefix in the logging to make the parsing easier.
Jira Issues:
-
Checklist
=> Add null-character as prefix in logs to make parsing easier

command_line_assistant/commands/history.py, command_line_assistant/history/plugins/local.py, command_line_assistant/logger.py
=> Small sonarqube fixes

command_line_assistant/commands/history.py, command_line_assistant/daemon/database/models/base.py, command_line_assistant/daemon/database/repository/base.py, command_line_assistant/history/plugins/local.py
=> Fix created_at dates for history and chat

command_line_assistant/commands/feedback.py, command_line_assistant/commands/shell.py, command_line_assistant/exceptions.py, command_line_assistant/initialize.py, command_line_assistant/utils/cli.py, docs/source/commands/feedback.rst, docs/source/commands/index.rst, tests/commands/test_feedback.py
Jira Issues:
- [RSPEED-588](https://issues.redhat.com/browse/RSPEED-588)
Checklist
=> [RSPEED-588] Feedback mechanism

command_line_assistant/commands/chat.py, data/release/man/c.1, data/release/man/clad.8, docs/source/man/command-line-assistant.1.rst
=> Update manpages with recent information

command_line_assistant/commands/feedback.py, data/release/man/c.1
=> Hide submit parameter from feedback command

command_line_assistant/daemon/session.py, tests/commands/test_chat.py, tests/commands/test_feedback.py, tests/commands/test_history.py, tests/commands/test_shell.py, tests/config/schemas/test_database.py, tests/config/schemas/test_schema.py, tests/daemon/database/models/test_base.py, tests/daemon/database/test_manager.py, tests/daemon/http/test_query.py, tests/daemon/http/test_session.py, tests/daemon/test_session.py, tests/dbus/interfaces/test_history.py, tests/dbus/interfaces/test_user.py, tests/rendering/decorators/test_colors.py, tests/rendering/decorators/test_text.py, tests/rendering/renders/test_interactive.py, tests/rendering/renders/test_markdown.py, tests/rendering/renders/test_spinner.py, tests/rendering/renders/test_text.py, tests/rendering/test_stream.py, tests/terminal/test_reader.py, tests/test_logger.py, tests/utils/test_files.py
=> Increase tests coverage

command_line_assistant/commands/chat.py, command_line_assistant/commands/feedback.py, tests/commands/test_feedback.py
Jira Issues:
- [RSPEED-751](https://issues.redhat.com/browse/RSPEED-751)
Checklist
=> [RSPEED-751] Fix typos in legal and feedback message

command_line_assistant/commands/chat.py, data/release/man/c.1, data/release/man/clad.8
=> Update --name help message to be more clear

command_line_assistant/commands/shell.py
=> Add message to indicate where the terminal capture is being recorded

data/release/xdg/config.toml
=> Update production endpoint to match AppSre

command_line_assistant/terminal/parser.py, command_line_assistant/terminal/reader.py, command_line_assistant/utils/files.py
Jira Issues:
- [RSPEED-767](https://issues.redhat.com/browse/RSPEED-767)
Checklist
=> [RSPEED-767] Fix inconsistency in reading the terminal output

command_line_assistant/config/schemas/database.py, tests/config/schemas/test_database.py
Jira Issues:
- [RSPEED-773](https://issues.redhat.com/browse/RSPEED-773)
Checklist
=> [RSPEED-773] Specify pymysql in the mysql connection string

data/release/systemd/clad.service, data/release/xdg/config.toml
=> Fix prod url

scripts/prepare_release.py
=> Update prepare-release-script to update docs version

command_line_assistant/daemon/http/query.py, command_line_assistant/initialize.py, tests/daemon/http/test_query.py, tests/test_initialize.py
Now the API has the ability to communicate back with us and have a better error to show to the users.
Jira Issues:
-
Checklist
=> Include better error information from API

data/release/systemd/clad.service
Add couple of systemd options to help improve the service security.
Jira Issues:
- [RSPEED-567](https://issues.redhat.com/browse/RSPEED-567)
Checklist
=> [RSPEED-567] Improve CLAD systemd unit security

command_line_assistant/history/base.py, command_line_assistant/history/manager.py, command_line_assistant/history/plugins/local.py, tests/dbus/interfaces/test_history.py
Missing validations made the tests fails and not behave correctly.
Jira Issues:
-
Checklist
=> Fix unit-tests for history interface

command_line_assistant/commands/feedback.py, data/release/man/c.1, data/release/man/clad.8, data/release/xdg/config.toml, docs/source/man/clad.8.rst, docs/source/man/command-line-assistant.1.rst
=> Update manpages for `c` and `clad`

Makefile, scripts/prepare_release.py
=> Update prepare release with custom features

command_line_assistant/daemon/http/session.py, tests/daemon/http/test_session.py
Jira Issues:
- [RSPEED-789](https://issues.redhat.com/browse/RSPEED-789)
Checklist
=> [RSPEED-789] Simpify cert loading

docs/source/man/clad.8.rst, docs/source/man/command-line-assistant.1.rst
=> Fix typos and wording on manpages

command_line_assistant/commands/shell.py, command_line_assistant/integrations.py, data/release/man/c.1, docs/source/man/command-line-assistant.1.rst
Using the CTRL+J is used by the venv, try to use different key that could be unused.
https://www.computerhope.com/ushort.htm
=> Change the interactive binding to ctrl+g, as ctrl+j is used by venv

data/release/dbus/com.redhat.lightspeed.conf
=> Add comment about RBAC in dbus policy

data/release/dbus/com.redhat.lightspeed.conf, docs/source/man/clad.8.rst
Fix typoo in the com.redhat.lightspeed.conf
=> [TYPOO] Fix typoo in the com.redhat.lightspeed.conf

.pre-commit-config.yaml
=> Fix rpmlint hook to check for .spec files

CONTRIBUTING.md
Include instructions in the CONTRIBUTING doc on what packages are
required to compile the Python packages.
Jira Issues:
-
Checklist
=> Document the system header requirements

data/development/config/command-line-assistant/config.toml
=> Revert config.toml to use localhost instead of MPP endpoint

command_line_assistant/initialize.py
=> Disable colors in output

command_line_assistant/initialize.py
Reverts rhel-lightspeed/command-line-assistant#324
=> Revert "Disable colors in output"

command_line_assistant/commands/chat.py, command_line_assistant/commands/feedback.py, command_line_assistant/commands/history.py, command_line_assistant/commands/shell.py, command_line_assistant/utils/cli.py, data/release/man/c.1, data/release/man/clad.8, docs/source/man/clad.8.rst
The fixes applied here are based on the recommendations by Eliane Pereira.
Jira Issues:
- [RSPEED-844](https://issues.redhat.com/browse/RSPEED-844)
Checklist
=> [RSPEED-844] Apply fixes to commands description and manpage in general

command_line_assistant/commands/chat.py, tests/commands/test_chat.py
Both --name and --description were not being tracked properly. This patch tries to fix it by removing them from the default argument in argparse and use a constant for that.
In case the user overrides it, it should work just as fine.
Jira Issues:
- [RSPEED-781](https://issues.redhat.com/browse/RSPEED-781)
Checklist
=> [RSPEED-781] Fix chat description and name defaults

.packit.yaml, data/release/selinux/clad.fc, data/release/systemd/clad.service, packaging/command-line-assistant.spec
=> Add fedora42 builds in COPR

command_line_assistant/config/schemas/backend.py, tests/config/schemas/test_schema.py
Honor the http_proxy environment variables.
Fixes: #363
=> Honor the http_proxy environment variables

Makefile, command_line_assistant/constants.py, data/release/man/c.1, data/release/man/clad.8, data/release/selinux/clad.te, docs/source/conf.py, packaging/command-line-assistant.spec, pyproject.toml
=> Prepare for release v0.4.0

scripts/prepare_release.py
Update the prepare-release script to be convenient and create a new branch before the modifications
Jira Issues:
-
Checklist
=> Update prepare-release script to create a new branch

.packit.yaml
Update .packit.yaml target distros
Jira Issues:
-
Checklist
=> Update .packit.yaml target distros

command_line_assistant/commands/chat.py
Jira Issues:
- [RSPEED-1564](https://issues.redhat.com/browse/RSPEED-1564)
Checklist
=> [RSPEED-1564] Add horizontal lines back

renovate.json
The best practices configuration from Renovate provides several benefits, including pinning container SHAs and pinning testing requirements.
=> renovate: Enable best practices config

Makefile, command_line_assistant/constants.py, container-images/default.Containerfile, data/release/man/c.1, data/release/man/clad.8, data/release/selinux/clad.te, docs/source/conf.py, packaging/command-line-assistant.spec, pyproject.toml, tests/dbus/interfaces/test_chat.py
=> Prepare for release v0.4.1
